### ISSUE TITLE
Apply Opacity on behind Image.

### ISSUE THREAD

**Issue by danish5454** [Skipperlla/rn-swiper-list#14]
I want to apply Opacity like when we are swipe left/right the card then previous card should be animate with opacity.

**Comment by Skipperlla** [comment]
@danish5454  Is there a source you can cite as an example from anywhere? I don't quite understand what you mean

**Comment by danish5454** [comment]
@dancixx What I mean when user translateX the card to left/right the card that is behind should be interpolate with opacity like 0.4 to 1 or I.

**Comment by Skipperlla** [comment]
@danish5454 a feature came to my mind about the suggestion you mentioned, I will add this feature when I have a free time.

**Comment by danish5454** [comment]
@Skipperlla Thanks 🙏🙏
