### ISSUE TITLE
Swipe Issue

### ISSUE THREAD

**Issue by danish5454** [Skipperlla/rn-swiper-list#16]
Swiping is really hard in real device.

I want to swipe left and right when user swipe the card almost 50% or 40%. how that's possible.

**Comment by Skipperlla** [comment]
@danish5454 https://github.com/Skipperlla/rn-swiper-list?tab=readme-ov-file#rotation-animation-props check this out `Rotation animation Props` title

**Comment by Skipperlla** [comment]
please come back to the issue afterwards and I will close the issue if it worked for you.
