### ISSUE TITLE
Swiper is too laggy.

### ISSUE THREAD

**Issue by danish5454** [Skipperlla/rn-swiper-list#17]
When  I add `FlatList`, `pinar`, any images `carousel` with direction horizontal inside `renderCard` then swiper is too laggy.
I'm rendering 20 cards and its sometimes stuck in 10th card in `SUMSUNG S23 Ultra`

**Comment by Skipperlla** [comment]
Can you make a video so I can see it in more detail? @danish5454

**Comment by danish5454** [comment]
https://github.com/Skipperlla/rn-swiper-list/assets/132438054/d554fe53-7020-4a78-922a-d669134569be

**Comment by danish5454** [comment]
@Skipperlla If I remove Image its work fine or If I just show one image then it also working fine.
currently we are showing 5 images in carousel.
