### ISSUE TITLE
(re)add Swipe Bottom

### ISSUE THREAD

**Issue by PEZO19** [Skipperlla/rn-swiper-list#22]
`rn-tinder-card` did have such functionality :)

**Comment by Skipperlla** [comment]
I thought it would not be used much, so I removed it and I will add it. 😄

**Comment by Skipperlla** [comment]
https://github.com/Skipperlla/rn-swiper-list/pull/27

**Comment by PEZO19** [comment]
@Skipperlla So cool, thank you! :)
