### ISSUE TITLE
Swipe amount

### ISSUE THREAD

**Issue by pekanct** [Skipperlla/rn-swiper-list#29]
Please, can you add the amount of the swipe to the onSwipeActive event? I would like to add an animation that is played based on the swipe but at the moment I have not found any way to derive this value.

Thankyou 🙏🏻

**Comment by Skipperlla** [comment]
by scroll amount you mean activeIndex, right? I don't quite understand what you said @pekanct

**Comment by pekanct** [comment]
I mean the amount of movement performed. For example, if I hold my finger down and stop the animation halfway, this value will be 50%. 100% is when the final event (eg. onSwipeRight) is triggered.. The same principle that is currently used for the opacity of the overlay, the further you swipe the card, the more the opacity of the overlay label increases.
 @Skipperlla  I hope I was clearer now

**Comment by Skipperlla** [comment]
I'm a little busy at the moment, if I have time I will add it

**Comment by leo0grau** [comment]
Hello @Skipperlla ,
Has this been added to the library yet, or is it on your roadmap? If there’s a planned approach or timeline, I’d appreciate any details. Thank you for your work on this project.
