### ISSUE TITLE
Question (Animation speed)

### ISSUE THREAD

**Issue by borscs** [Skipperlla/rn-swiper-list#30]
I want to slow down the speed of the swipe animations, how can I do this?

**Comment by Skipperlla** [comment]
> 
> 
> I want to slow down the speed of the swipe animations, how can I do this?

Unfortunately, this feature is not available at the moment, but I will be adding it to a cumulative update this weekend.

**Comment by Skipperlla** [comment]
this weekend I will look at this and all other issues and pr's and close them, I apologize to all of you one by one for keeping you waiting so long @borscs

**Comment by backendpapa1** [comment]
hey @Skipperlla  we still waiting, amazing lib tho

**Comment by Skipperlla** [comment]
hey i added this feature today i will post an update at the end of the day stay tuned @backendpapa1 @borscs https://github.com/Skipperlla/rn-swiper-list/pull/43
