### ISSUE TITLE
On Android the card is stuck, can not swipe

### ISSUE THREAD

**Issue by thachlee2708** [Skipperlla/rn-swiper-list#31]
i tested on ios, it works fine on ios simulator
But on android the card doesn't move when i touch and drag it, the card only moves when i press the button(like the heart button)
Do you know what the problem is?

https://github.com/user-attachments/assets/baf8548d-f943-42ab-ab7e-b084712a213a

**Comment by Skipperlla** [comment]
Does this problem only happen when gesturing? If so, I'm making a note of this to fix it in the next update. @thachlee2708

**Comment by Skipperlla** [comment]
@thachlee2708 I will debug this, but can you at least post the sample code you used in this video?

**Comment by Skipperlla** [comment]
this weekend I will look at this and all other issues and pr's and close them, I apologize to all of you one by one for keeping you waiting so long @thachlee2708

**Comment by deependra53** [comment]
Any update @Skipperlla regarding this bug i am stuck with this?... it works smooth for IOS but for android it get stuck on swipe.....

**Comment by Skipperlla** [comment]
@deependra53 @thachlee2708 If you wrapped the component in a view, you may have encountered this problem, I did not find a problem in android when I tested it right now.

**Comment by deependra53** [comment]
import React, {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import {
  Alert,
  Dimensions,
  FlatList,
  Image,
  ImageBackground,
  ScrollView,
  StyleSheet,
  Stylesheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {COLORS} from '../../constants/colors';
import {FONTS} from '../../constants/fonts';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';
import {IMAGES, SVG_IMAGES} from '../../constants/images';
import CommonHeader from '../../components/CommonHeader';
import SearchInput from '../../components/SearchInput';
import TextInputComponent from '../../components/TextInputComponent';
import BtnPrimary from '../../components/BtnPrimary';
import LinearGradient from 'react-native-linear-gradient';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {Swiper} from 'rn-swiper-list';
import NoResults from './EmptyView';
import MatchModel from './MatchModel';
import SendMessageBtn from '../../components/TextInputComponent';
import FilterModal from './FilterModal';
import MessageModal from './MessageModal';

const userData = [
  {
    id: '1',
    uri: IMAGES.Card1_Img,
    name: 'Hillary, 24',
    active: 'Active now',
    new: 0,
    liked: 0,
  },
  {
    id: '2',
    uri: IMAGES.Card2_Img,
    name: 'Ruby, 24',
    active: 'Active now',
    new: 1,
    liked: 0,
  },
  {
    id: '3',
    uri: IMAGES.Card3_Img,
    name: 'Jane, 24',
    active: 'Active now',
    new: 0,
    liked: 1,
  },
  {
    id: '4',
    uri: IMAGES.Card4_Img,
    name: 'Ruth, 24',
    active: 'Active now',
    new: 1,
    liked: 0,
  },
  {
    id: '5',
    uri: IMAGES.Card1_Img,
    name: 'Hillary, 24',
    active: 'Active now',
    new: 0,
    liked: 0,
  },
  {
    id: '6',
    uri: IMAGES.Card2_Img,
    name: 'Ruby, 24',
    active: 'Active now',
    new: 1,
    liked: 0,
  },
];

const IMAGES_ARRAY = [
  {
    img_url: [
      IMAGES.Profile_Img,
      IMAGES.Card1_Img,
      IMAGES.Card2_Img,
      IMAGES.Profile_Img,
    ],
  },
  {img_url: [IMAGES.Card1_Img, IMAGES.Card2_Img, IMAGES.Card3_Img]},
  {img_url: [IMAGES.Card2_Img, IMAGES.Card3_Img, IMAGES.Card4_Img]},
  {img_url: [IMAGES.Card3_Img, IMAGES.Card4_Img, IMAGES.Card2_Img]},
  {
    img_url: [
      IMAGES.Card1_Img,
      IMAGES.Card2_Img,
      IMAGES.Card3_Img,
      IMAGES.Profile_Img,
    ],
  },
];

const TabHomeScreen = () => {
  const navigation = useNavigation();
  const ref = useRef();
  const [currentIndex, setCurrentIndex] = useState(0);
  const totalSteps = IMAGES_ARRAY.length;
  const [isLoading, setIsLoading] = useState(true);
  const {height: screenHeight} = Dimensions.get('window');
  const isProMax = screenHeight > 850;
  const isMini = screenHeight < 830;
  const isPro = screenHeight > 850 && screenHeight < 900;
  const height = Dimensions.get('screen').height;
  const [isNoResults, setIsNoResults] = useState(false);
  const [isLikeLimitExceeded, setIsLikeLimitExceeded] = useState(false);
  const [likeCount, setLikeCount] = useState(0);
  const [isMessageLimitExceeded, setIsMessageLimitExceeded] = useState(false);
  const [noResultsData, setNoResultsData] = useState({
    title: 'Oh no, looks like \nyou have run out of people!',
    subtitle: 'Update your search filters to see more profiles.',
    buttonText: 'Update filters',
  });
  const [isMatchVisible, setIsMatchVisible] = useState(false);
  const [matchedPerson, setMatchedPerson] = useState(null);
  const [isFilterModalVisible, setIsFilterModalVisible] = useState(false);
  const [isMessageModalVisible, setIsMessageModalVisible] = useState(false);
  const [messageValue, setMessageValue] = useState('');

  const {width} = Dimensions.get('window'); // Get device width
  const [numColumns, setNumColumns] = useState(1); // State to toggle columns
  const toggleColum = () => {
    // Toggle between 2 and 3 columns
    setNumColumns(prevNum => {
      if (prevNum === 3) {
        return 1;
      } else {
        return prevNum + 1;
      }
    });
  };
  // Use useMemo to optimize recalculation of itemWidth and height based on numColumns
  const {itemWidth, itemHeight} = useMemo(() => {
    const itemMargin = moderateScale(10);
    const calculatedWidth =
      (width - itemMargin * (numColumns + 2.4)) / numColumns;
    const calculatedHeight = numColumns
      ? Dimensions.get('window').height * 0.21
      : Dimensions.get('window').height * 0.17;
    return {itemWidth: calculatedWidth, itemHeight: calculatedHeight};
  }, [numColumns, width]);

  // Render User Data
  const renderItem = ({item}) => (
    <View
      style={[
        Styles.cardBox,
        {
          margin:
            numColumns === 3
              ? moderateScale(10) / 2.7
              : moderateScale(10) / 2.2,
        },
      ]}>
      <ImageBackground
        source={item.uri}
        style={[
          Styles.imageStyle,
          {
            width: itemWidth,
            height: numColumns === 3 ? 144 : 207,
            // padding: numColumns === 3 ? 9 : 13,
          },
        ]}>
        {/* Gradient overlay from bottom to top */}
        <LinearGradient
          colors={['transparent', 'transparent', 'rgba(0,0,0,0.8)']}
          style={[
            Styles.gradient,
            {
              position: 'absolute',
              width: '100%',
            },
          ]}
        />

        {item.new == 1 && (
          <View style={Styles.new}>
            <Text
              style={[
                Styles.newText,
                {
                  fontSize: numColumns === 3 ? scale(8) : scale(10),
                },
              ]}>
              New
            </Text>
          </View>
        )}

        {item.liked == 1 && (
          <View
            style={[
              Styles.new,
              {
                backgroundColor: 'rgba(255,77,103,0.8)',
              },
            ]}>
            <Text
              style={[
                Styles.newText,
                {
                  fontSize: numColumns === 3 ? scale(8) : scale(12),
                },
              ]}>
              Likes you!
            </Text>
          </View>
        )}

        <SVG_IMAGES.Bluebadge_SVG
          width={numColumns ? 25 : 25}
          style={Styles.badgeStyle}
        />

        <View style={{padding: numColumns === 3 ? 9 : 13}}>
          <Text
            style={[
              Styles.title,
              {
                fontSize: numColumns === 3 ? scale(15) : scale(19),
              },
            ]}>
            {item.name}
          </Text>
          <View style={Styles.activeFlex}>
            <Text
              style={[
                Styles.activenow,
                {
                  fontSize: numColumns === 3 ? scale(9) : scale(12),
                },
              ]}>
              {item.active}
            </Text>
            <View style={Styles.online} />
          </View>
        </View>
      </ImageBackground>
      <View
        style={[
          Styles.btnBox,
          Styles.btnBox1,
          {
            padding: numColumns === 3 ? 6 : 10,
            gap: numColumns === 3 ? 7 : 9,
          },
        ]}>
        <BtnPrimary
          isNormal={true}
          style={{
            flexGrow: 1,
            height: numColumns === 3 ? 37 : 52,
            borderRadius: 8,
            backgroundColor: 'rgba(0,0,0,0.4)',
            paddingHorizontal: numColumns === 3 ? 10 : 15,
          }}
          btnStyle={{
            paddingTop: numColumns === 3 ? 0 : 10,
          }}
          icon={
            <SVG_IMAGES.Dislikebutton_SVG
              width={numColumns === 3 ? 19 : 24}
              height={numColumns === 3 ? 19 : 24}
            />
          }
        />
        <BtnPrimary
          isNormal={true}
          style={{
            flexGrow: 1,
            height: numColumns === 3 ? 37 : 52,
            borderRadius: 8,
            backgroundColor: 'rgba(0,0,0,0.4)',
            paddingHorizontal: numColumns === 3 ? 10 : 15,
          }}
          btnStyle={{
            paddingTop: numColumns === 3 ? 0 : 10,
          }}
          icon={
            item.new == 1 ? (
              <SVG_IMAGES.Heart1_SVG
                width={numColumns === 3 ? 19 : 24}
                height={numColumns === 3 ? 19 : 24}
              />
            ) : (
              <SVG_IMAGES.Heart_SVG
                width={numColumns === 3 ? 19 : 24}
                height={numColumns === 3 ? 19 : 24}
              />
            )
          }
        />
      </View>
    </View>
  );

  // slider UI components
  const renderCard = (image, index) => {
    const [currentImage, setCurrentImage] = useState(0);
    console.log('currentImage :', currentImage);

    const handleLeftClick = () => {
      console.log('handleLeftClick :');
      if (currentImage > 0) {
        console.log(' handleLeftClick index :', index);
        setCurrentImage(prev => prev - 1);
      }
    };

    const handleRightClick = () => {
      console.log('handleRightClick :');
      if (currentImage < image?.img_url?.length - 1) {
        console.log(' handleRightClick index :', index);
        setCurrentImage(prev => prev + 1);
      }
    };
    return (
      <View style={Styles.renderCardContainer}>
        <TouchableOpacity
          style={[Styles.touchableArea, {left: 0}]}
          onPress={handleLeftClick}
        />
        <TouchableOpacity
          style={[Styles.touchableArea, {right: 0}]}
          onPress={handleRightClick}
        />
        <ImageBackground
          source={image.img_url?.[currentImage]}
          style={Styles.cardSwipe}>
          {/* Gradient overlay from bottom to top */}
          <LinearGradient
            colors={['transparent', 'rgba(0,0,0,0.8)']}
            style={Styles.gradient}
          />
          <View style={[Styles.activeFlex, Styles.activeFlex1]}>
            <View style={[Styles.online, Styles.online1]} />
            <Text
              style={[
                Styles.activenow,
                {
                  fontSize: scale(15),
                  fontFamily: FONTS.Samsungsharpsans_Bold,
                },
              ]}>
              Online
            </Text>
          </View>
          <View
            style={[
              Styles.new,
              {
                right: 10,
                top: 10,
                backgroundColor: COLORS.white,
              },
            ]}>
            <Text
              style={[
                Styles.newText,
                {
                  fontSize: scale(12),
                  color: COLORS.black,
                },
              ]}>
              2552 km
            </Text>
          </View>
          <View style={Styles.cardSwipeBody}>
            <View
              style={[
                Styles.new,
                {
                  right: 0,
                  top: 0,
                  position: 'relative',
                  width: 50,
                  marginBottom: verticalScale(5),
                },
              ]}>
              <Text
                style={[
                  Styles.newText,
                  {
                    fontSize: scale(10),
                    textAlign: 'center',
                    paddingVertical: 2,
                  },
                ]}>
                New
              </Text>
            </View>
            <Text
              style={[
                Styles.title,
                {
                  fontSize: scale(32),
                  marginBottom: verticalScale(2),
                },
              ]}>
              {userData[index]?.name || 'Hillary, 24'}
            </Text>
            <View style={[Styles.activeFlex]}>
              <Text
                style={[
                  Styles.activenow,
                  {
                    fontSize: scale(15),
                    fontFamily: FONTS.Samsungsharpsans_Medium,
                  },
                ]}>
                California, USA
              </Text>
              <SVG_IMAGES.Bluebadge_SVG
                width={22}
                style={[
                  Styles.badgeStyle,
                  {
                    position: 'relative',
                    top: 0,
                    left: 0,
                    marginHorizontal: 5,
                  },
                ]}
              />
            </View>
          </View>
          <TouchableOpacity style={[Styles.infoIcon]}>
            <SVG_IMAGES.Info_SVG />
          </TouchableOpacity>

          {/* Dot Swiper */}
          <View style={Styles.dotSwiper}>
            {image?.img_url?.map((item, index) => (
              <View
                key={index}
                style={[
                  Styles.dotSwiperItem,
                  {
                    width:
                      Dimensions.get('screen').width *
                      (0.75 / image?.img_url?.length),
                  },
                  currentImage === index && Styles.activeDot,
                ]}
              />
            ))}
          </View>
        </ImageBackground>
      </View>
    );
  };

  const OverlayLabelRight = useCallback(() => {
    return (
      <View
        style={[
          Styles.overlayLabelContainer,
          {
            // backgroundColor: 'green',
            borderWidth: 7,
            borderColor: '#FF4D67',
          },
        ]}
      />
    );
  }, []);

  const OverlayLabelLeft = useCallback(() => {
    return (
      <View
        style={[
          Styles.overlayLabelContainer,
          {
            // backgroundColor: 'red',
            borderWidth: 7,
            borderColor: '#56AFFF',
          },
        ]}
      />
    );
  }, []);

  const OverlayLabelTop = useCallback(() => {
    return (
      <View
        style={[
          Styles.overlayLabelContainer,
          {
            backgroundColor: '',
          },
        ]}
      />
    );
  }, []);

  const handleIndexChange = index => {
    setCurrentIndex(index);
    console.log('Current Active index', index);
  };

  const handleLikeButtonClick = () => {
    setLikeCount(prevCount => {
      const newCount = prevCount + 1;
      if (newCount >= 4) {
        setIsNoResults(true);
        setIsLikeLimitExceeded(true);
      }
      return newCount;
    });
  };

  useEffect(() => {
    if (isLikeLimitExceeded) {
      setIsNoResults(true);
      setNoResultsData({
        title: 'Oh no, looks like you’ve run out of likes!',
        subtitle:
          'We only allow up to 20 likes per day, please come back tomorrow to continue swiping.',
        buttonText: 'Go Back',
      });
    } else if (isMessageLimitExceeded) {
      setIsNoResults(true);
      setNoResultsData({
        title: 'Oh no, looks like you’ve run out of messages!',
        subtitle:
          'We only allow up to 3 messages to unknown people per day, please come back tomorrow to continue sending introductions.',
        buttonText: 'Go Back',
      });
    }
  }, [isLikeLimitExceeded, isMessageLimitExceeded]);

  return (
    <GestureHandlerRootView
      style={[
        Styles.container,
        {
          height: isPro
            ? '64.5%'
            : isMini
            ? '61%'
            : isProMax
            ? '67.5%'
            : height * 0.44,
        },
      ]}>
      {/* <View style={[Styles.subContainer, { backgroundColor: 'red' }]}> */}
      <Swiper
        ref={ref}
        cardStyle={Styles.cardStyle}
        data={IMAGES_ARRAY}
        renderCard={renderCard}
        onIndexChange={handleIndexChange}
        onSwipeRight={cardIndex => {
          console.log('cardIndex', cardIndex);
        }}
        onSwipedAll={() => {
          console.log('onSwipedAll');
          ref.current?.swipeBack();
        }}
        onSwipeLeft={cardIndex => {
          console.log('onSwipeLeft', cardIndex);
        }}
        onSwipeTop={cardIndex => {
          console.log('onSwipeTop', cardIndex);
        }}
        OverlayLabelRight={OverlayLabelRight}
        OverlayLabelLeft={OverlayLabelLeft}
        OverlayLabelTop={OverlayLabelTop}
        onSwipeActive={() => {
          console.log('onSwipeActive');
        }}
        onSwipeStart={() => {
          console.log('onSwipeStart');
        }}
        onSwipeEnd={() => {
          console.log('onSwipeEnd');
        }}
      />
      {/* card content */}
      {/* </View> */}
    </GestureHandlerRootView>
  );
};

export default TabHomeScreen;

const Styles = StyleSheet.create({
  touchableArea: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    zIndex: 10,
  },
  safeArea: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  wrapper: {
    padding: moderateScale(15),
    paddingTop: verticalScale(0),
    paddingBottom:
      Platform.OS === 'ios'
        ? Dimensions.get('window').height * 0.12
        : Dimensions.get('window').height * 0.12,
  },
  // Heading
  bgImgstyle: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height,
  },
  // Search
  searchBox: {
    // paddingHorizontal: moderateScale(5),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(12),
    marginBottom: verticalScale(15),
    zIndex: 0,
  },
  iconBox: {
    width: 48,
    height: 48,
    backgroundColor: COLORS.rgbacolor,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // btnBox
  btnBox: {
    marginTop: verticalScale(13),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(12),
    justifyContent: 'space-between',
  },
  // cardSwipe
  cardSwipe: {
    flex: 1,
    width: '100%',
    height: Dimensions.get('screen').height * 0.47,
    marginBottom: verticalScale(15),
    overflow: 'hidden',
    borderRadius: 15,
    flexDirection: 'column',
    justifyContent: 'flex-end',
    zIndex: 0,
  },
  cardSwipeBody: {
    padding: moderateScale(15),
  },
  imageStyle: {
    width: 160,
    borderRadius: 6,
    justifyContent: 'flex-end',
  },
  // Card
  cardBox: {
    borderRadius: 6, // 7.5
    overflow: 'hidden',
    marginBottom: verticalScale(8),
  },
  btnBox1: {
    backgroundColor: COLORS.rgbacolor,
    marginTop: 0,
    padding: 10,
  },
  gradient: {
    position: 'absolute', // To overlay the gradient on top of the image
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    // zIndex: 1,
    height: '100%',
    width: '100%',
  },
  title: {
    fontFamily: FONTS.Samsungsharpsans_Bold,
    color: COLORS.white,
    marginBottom: verticalScale(3),
  },
  // activeFlex
  activeFlex: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  activeFlex1: {
    position: 'absolute',
    left: 15,
    top: 15,
  },
  activenow: {
    fontFamily: FONTS.Samsungsharpsans,
    color: COLORS.white,
  },
  online: {
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: COLORS.green,
    // top: 1,
  },
  online1: {
    width: 11,
    height: 11,
  },
  badgeStyle: {
    position: 'absolute',
    top: 6,
    left: 6,
  },
  // New
  new: {
    position: 'absolute',
    top: 10,
    right: 6,
    backgroundColor: 'rgba(106,251,105,0.8)',
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  newText: {
    fontFamily: FONTS.Samsungsharpsans_Bold,
    color: COLORS.white,
  },
  // Info
  infoIcon: {
    position: 'absolute',
    right: 15,
    bottom: 32,
    top: 'auto',
  },
  //
  dotSwiper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: verticalScale(12),
    gap: 10,
  },
  dotSwiperItem: {
    backgroundColor: COLORS.white,
    height: 4,
    borderRadius: 100,
    opacity: 0.5,
  },
  activeDot: {
    opacity: 1,
  },

  // Card Header
  cardHeaderContent: {
    position: 'absolute',
    left: 15,
    top: 5,
    left: 0,
    right: 0,
    bottom: 0,
  },
  cardBodyContent: {
    marginTop: verticalScale(170),
  },
  progressBarContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    width: '90%',
  },
  progressStep: {
    width: 20,
    height: 4,
    backgroundColor: 'grey',
    marginHorizontal: 2,
    borderRadius: 2,
  },
  activeStep: {
    backgroundColor: '#fff',
  },
  // Slider styles
  container: {
    height: '65%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    position: 'relative',
    zIndex: 9999,
  },
  buttonsContainer: {
    flexDirection: 'row',
    bottom: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    height: 80,
    borderRadius: 40,
    marginHorizontal: 20,
    aspectRatio: 1,
    backgroundColor: '#3A3D45',
    elevation: 4,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowOffset: {
      width: 0,
      height: 4,
    },
  },
  buttonText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  cardStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
    marginVertical: 20,
    zIndex: 11, // Ensure this is the highest to be swipeable
    position: 'relative',
  },
  renderCardContainer: {
    flex: 1,
    borderRadius: 15,
    height: '75%',
    width: '100%',
  },
  renderCardImage: {
    height: '100%',
    width: '100%',
    borderRadius: 15,
  },
  subContainer: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9,
  },
  overlayLabelContainer: {
    width: '100%',
    height: '96%',
    borderRadius: 15,
  },
});


 
here is my component @Skipperlla

**Comment by deependra53** [comment]
[Uploading Screen Recording 2024-12-17 at 11.42.26 PM.mov.zip…]()

**Comment by deependra53** [comment]
https://drive.google.com/file/d/1l7s-vShDA3ALdjY2W1yH0crVT_yetBLY/view?usp=sharing
link for video reference
