### ISSUE TITLE
[Request] How to get current active Index

### ISSUE THREAD

**Issue by umangloria** [Skipperlla/rn-swiper-list#32]
First of all thank you for the amazing package, This is beautiful and working fine for most options.

However I think having a callback that provides current active index will be helpful as currently I tried to manage index by saving value of index on  `onSwipeLeft` and `onSwipeRight` but the thing is there are still scenarios like currently there is no callback for `onSwipeBack`. 
I also looked whether we are getting `onSwipeEnd` or other methods triggered when using `ref.current?.swipeBack();` but obviously as we are not using gesture it is not getting triggered. and even if it was triggered then also currently `onSwipeEnd` is not returning the index.
So I think if we can have something like `onChangeIndex` or similar that will be really helpful.
I can also help with the implementation and PR.

**Comment by Skipperlla** [comment]
you can open a pr for this feature, because of my general busyness, I can not look at the kutuphane too much, so opening a pr will help me a lot. @umangloria

**Comment by umangloria** [comment]
@Skipperlla Opened PR

**Comment by Skipperlla** [comment]
I am very busy at the moment, I will check and confirm as soon as possible.
