### ISSUE TITLE
(Question) How to make the swiper cards swiping in a loop?

### ISSUE THREAD

**Issue by gzhai5** [Skipperlla/rn-swiper-list#37]
Thanks so much for sharing this repo & code for RN card swiper.
I am new to here, and don't know how to adjust the props so that the swiper cards could be in a loop, when you swipe to the last indexed card, the next one will be the first card.

**Comment by JohnnyBoySou** [comment]
+1

**Comment by Skipperlla** [comment]
this weekend I will look at this and all other issues and pr's and close them, I apologize to all of you one by one for keeping you waiting so long @gzhai5 @JohnnyBoySou

**Comment by SergoGansta777** [comment]
> this weekend I will look at this and all other issues and pr's and close them, I apologize to all of you one by one for keeping you waiting so long @gzhai5 @JohnnyBoySou

So, any news?

**Comment by Skipperlla** [comment]
@SergoGansta777 unfortunately I couldn't meet the promised deadline, I'm still working on it, everything will be ready before the end of this month.

**Comment by romainchkr** [comment]
Hey ! I can't wait to have that feature :) 
Great package btw ! Keep it up :)

**Comment by Skipperlla** [comment]
hey i added this feature today i will post an update at the end of the day stay tuned @backendpapa1 @borscs https://github.com/Skipperlla/rn-swiper-list/pull/44 @romainchkr @SergoGansta777 @JohnnyBoySou @gzhai5
